<?php

return [
    'DASHBOARD' => 'dashboard',
    'MUTATIONS' => 'mutations',
    'EXPENSES' => 'expenses',
    'INCOMES' => 'incomes',
    'RECEIVABLES' => 'receivables',
    'SUMMARY' => 'summary',
    'CASH_COUNTER' => 'cash_counter',
    'BILLS' => 'bills',
    'PRODUCTS' => 'products',
    'CATEGORIES' => 'categories',
    'STOCK_IN' => 'stock_in',
    'POS' => 'pos',
    'STOCK_OPNAME' => 'stock_opname',
    'STOCK_REPORT' => 'stock_report',
    'SALES_REPORT' => 'sales_report',
    'ACCOUNTS' => 'accounts',
    'CUSTOMERS' => 'customers',
    'REPORTS' => 'reports',
    'RETURNS' => 'returns',
    'PRINT_ORDERS' => 'print_orders',
    'REPAIR_SERVICES' => 'repair_services',
];
